// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2-jetWGV8vy8KCeQ4kv597aBCstiyKg',
    appId: '1:528838904274:web:f09a5551aa548cca26200b',
    messagingSenderId: '528838904274',
    projectId: 'todo-auth-57585',
    authDomain: 'todo-auth-57585.firebaseapp.com',
    storageBucket: 'todo-auth-57585.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bICmIxWHuhgeO6tPQL-DYCOosKHt5Rw',
    appId: '1:528838904274:android:a02af9f7430ff82626200b',
    messagingSenderId: '528838904274',
    projectId: 'todo-auth-57585',
    storageBucket: 'todo-auth-57585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH26NsocyjecCRCfvKJ_BfhLlHmDr5f3I',
    appId: '1:528838904274:ios:765c32fc1450700126200b',
    messagingSenderId: '528838904274',
    projectId: 'todo-auth-57585',
    storageBucket: 'todo-auth-57585.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH26NsocyjecCRCfvKJ_BfhLlHmDr5f3I',
    appId: '1:528838904274:ios:765c32fc1450700126200b',
    messagingSenderId: '528838904274',
    projectId: 'todo-auth-57585',
    storageBucket: 'todo-auth-57585.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2-jetWGV8vy8KCeQ4kv597aBCstiyKg',
    appId: '1:528838904274:web:224ee33f660bd61626200b',
    messagingSenderId: '528838904274',
    projectId: 'todo-auth-57585',
    authDomain: 'todo-auth-57585.firebaseapp.com',
    storageBucket: 'todo-auth-57585.firebasestorage.app',
  );
}
